### PR TITLE
Rewrote to use async and await

### PR DESCRIPTION
**Pull request by egamma**
I rewrote the code to use async and await and things seem to work now.

### CODE REVIEW

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@egamma thank you very much for taking the time to do this!

In addition to the information that I got from this [StackOverflow question](https://stackoverflow.com/questions/45111482) I think I have all the information that I need to continue.

**Comment by egamma** [comment]
@gep13 you are welcome. 

The tips from @mjbvz to enable more checking in the tsconfig mentioned on SO are really good ones, for example, here is a tsconfig for an extension I maintain https://github.com/Microsoft/vscode-npm-scripts/blob/master/tsconfig.json  (I just noticed that I should enable the strictNullCheck as well.

**Comment by gep13** [comment]
@egamma yip agreed, I will use them as defaults going forward, as I think they make a lot of sense.

**Pull request merged**
